//
// Created by james on 7/19/2024.
//

#ifndef LOW_LATENCY_TRADING_SYSTEM_101_ORDER_SERVER_H
#define LOW_LATENCY_TRADING_SYSTEM_101_ORDER_SERVER_H


class order_server {

};


#endif //LOW_LATENCY_TRADING_SYSTEM_101_ORDER_SERVER_H
